name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Run Maven tests
        working-directory: ./backend
        run: mvn test
        
      # SpotBugs 检查暂时跳过，等CI/CD跑通后再启用
      # - name: Run SpotBugs
      #   working-directory: ./backend
      #   run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.6.0.0:check
        
      - name: Build backend
        working-directory: ./backend
        run: mvn clean compile

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --watch=false --coverage
        
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  build-verification:
    name: Build Verification
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build backend
        working-directory: ./backend
        run: mvn clean package -DskipTests
        
      - name: Build frontend
        working-directory: ./frontend
        run: npm ci && npm run build
        
      - name: Verify builds
        run: |
          echo "Checking backend build..."
          ls -la backend/target/*.jar
          echo "Checking frontend build..."
          ls -la frontend/dist/

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [build-verification]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: airline-order-backend:latest
          
      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: airline-order-frontend:latest
